---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - WEBUI_PORT=8088
      - TORRENTING_PORT=6881
    volumes:
      - /home/shiva/dockerVolumes/qbittorrent/appdata:/config
      - /home/shiva/dockerVolumes/qbittorrent/tdownloads:/downloads #optional
    ports:
      - 8088:8080
      - 6881:6881
      - 6881:6881/udp
    stop_grace_period: "10s" #optional
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    name: proxy-network
    external: true

