---
services:
  server:
    image: docker.gitea.com/gitea:1.26.4
    container_name: gitea
    env_file:
      - .env
    environment:
      - USER_UID: ${USER_ID:-1000}
      - USER_GID: ${USER_GID:-1000}
      - GITEA__database__DB_TYPE: mysql
      - GITEA__database__HOST: ${GITEA__database__HOST:-mariadb:3306}
      - GITEA__database__NAME: ${GITEA__database__NAME:-gitea}
      - GITEA__database__USER: ${GITEA__database__USER:-gitea}
      - GITEA__database__PASSWD: ${GITEA__database__PASSWD:-giteapassword}
    restart: always
    networks:
      - proxy-network
    volumes:
      - $HOME/dockerVolumes/gitea/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro


networks:
  proxy-network:
    name: proxy-network
    external: true
