services:
  priyankablog:
    image: wordpress:latest
    container_name: priyankablog 
    restart: unless-stopped
    ports:
      - '3030:80'
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
      - WORDPRESS_DB_NAME
    volumes:
      - $USER/dockerVolumes/priyankablog/wordpress:/var/www/html
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
    name: proxy-network
