services:
   tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN
    networks:
      - proxy-out-network #connecting to same Nginx proxy manager network

networks:
  proxy-out-network:
    external: true
    name: proxy-out-network

