services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP
    environment:
      - DB_MYSQL_HOST
      - DB_MYSQL_PORT
      - DB_MYSQL_USER
      - DB_MYSQL_PASSWORD
      - DB_MYSQL_NAME
      # Optional SSL (see section below)
      # DB_MYSQL_SSL: 'true'
      # DB_MYSQL_SSL_REJECT_UNAUTHORIZED: 'true'
      # DB_MYSQL_SSL_VERIFY_IDENTITY: 'true'
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - $HOME/dockerVolumes/npm/data:/data
      - $HOME/dockerVolumes/npm/letsencrypt:/etc/letsencrypt
    networks:
      - proxy-network
      - proxy-out-network

#  db:
#    image: 'mariadb:latest'
#    container_name: mariadb
#    restart: unless-stopped
#    environment:
#      - MYSQL_ROOT_PASSWORD
#      - MYSQL_DATABASE
#      - MYSQL_USER
#      - MYSQL_PASSWORD
#      - MARIADB_AUTO_UPGRADE
#    volumes:
#      - ./mysql:/var/lib/mysql
#    networks:
#      - proxy-network
#    ports:
#      - '9909:3306'

networks:
  proxy-network:
    external: true
    name: proxy-network
  proxy-out-network:
    external: true
    name: proxy-out-network

#volumes:
#  mysql:
#     driver: local
