#SPDX-License-Identifier: MIT-0
---
# tasks file for apt-packages

- name: update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install/Remove apt packages
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop: "{{ apt_packages }}"
  register: output

- name: display output
  ansible.builtin.debug:
    var: output.results

