[rapi]
raspberrypi.local #ansible_connection=ssh  ansible_user=shiva  ansible_ssh_private_key_file=~/.ssh/id_rapi

[rapi:vars]
ansible_connection=ssh
ansible_user=shiva
ansible_ssh_private_key_file=~/.ssh/id_rapi
ansible_python_interpreter=/usr/bin/python
