---
- name: Adding wifi profiles
  hosts: rapi
  gather_facts: no 
  vars_files: 
    - ../variables/wifi_profiles.yml
  roles:
    - role:  roles/add-wifi-profiles
      vars:
        role_wifi_profiles: "{{ wifi_profiles }}"
  tasks:
    - name: debug variable
      ansible.builtin.debug: 
        var: wifi_profiles
