---
- name: Adding wifi profiles
  hosts: "{{ variable_host | default('rapi') }}"
  gather_facts: no 
  roles:
    - role:  roles/add-wifi-profiles
      vars:
        role_wifi_profiles: "{{ wifi_profiles }}"
  tasks:
    - name: debug variable
      ansible.builtin.debug: 
        var: wifi_profiles
